<?php
	session_start();
	require_once('includes/database.php');
	db_connect();
	if(!$_SESSION['login']) {
		header("Location: index.php");
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Spirit Friday - Privacy Rights</title>
		<link rel="icon" type="image/jpg" href="images/favicon.jpg" />
		<link href="css/index.css" type="text/css" rel="stylesheet" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-31623743-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</head>
	<body>
		<div id="container">
			<div id="main_content">
				<div id="top_privacy">
					<img src="images/logo_gray.jpg" />
					<h2>Privacy Rights</h2>
				</div>
				<div id="main_privacy">
					<h1 class="center">Privacy Policy</h1>
					<p>We at <span class="bold">Spirit Friday, LLC</span> ("Spirit Friday," "we," "us," "our") know that our users ("you," "your") care about how your personal information is used and shared, and we take your privacy seriously. This Policy applies to your use of our website and any related services (the "Website") under the domain spiritfriday.com. <span class="bold">By visiting or using the Website or Services in any manner, you acknowledge that you accept the practices and policies outlined in this Privacy Policy, and you hereby consent that we will gather, use, and share your information in the following ways.</span></p>
					
					<h2 class="center">I.  Information Gathered by Us</h2>
					
					<p>We gather various types of Personal Information from our users, as explained more fully below. We may use this Personal Information to personalize and improve our services, to allow our users to set up a user account and profile, to contact users, to fulfill your requests for certain products and services, to analyze how users utilize the Website, and as otherwise set forth in this Privacy Policy. We may share certain types of Personal Information with third parties (described in this Section and in Section II below). We collect the following types of information:</p>
					
					<p>A.  Information Submitted by a user Spirit Friday collects personal information when you register or request information from us. The personal information we collect includes name, email address, password, and birth date.  You may change your personal information under settings by signing in to your Spirit Friday account and select the settings icon</p>
					
					<p>If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Site, we may collect such information into a file specific to you.</p>
					
					<p>You may also enter another person's email to share a product. In this circumstance, we collect only the email address from the recipient.</p>
					
					<p>B.  Non-submitted Information Collected</p>

					<p>The Website may also collect non-personal information not associated with your identity. We collect this data to improve the Website. The non-submitted information we collect includes IP, browser type and version, operating system, “cookie” information, time spent on the website, pages visited, and data transferred. “Cookies” are identifiers we transfer to your computer or mobile device that allow us to recognize your browser or mobile device and tell us how and when pages in our Website are visited and by how many people. You may be able to change the preferences on your browser or mobile device to prevent or limit your computer or device’s acceptance of cookies, but this may prevent you from taking advantage of some of our Website’s features. Our advertising partners may also transmit cookies to your computer or device, when you click on ads that appear on the Website. Also, if you click on a link to a third party website, such thirdparty may also transmit cookies to you. This Privacy Policy does not cover the use of cookies by any third parties.</p>
					
					<p>When we collect usage information (such as the numbers and frequency of visitors to the Website), we only use this data in aggregate form, and not in a manner that would identify you personally. For example, this aggregate data tells us how often users use parts of the Website, so that we can make the Website appealing to as many users as possible. We may also provide this aggregate information to our partners; our partners may use such information to understand how often and in what ways people use our Website, so that they, too, can provide you with an optimal experience. We never disclose aggregate information to a partner in a manner that would identify you personally.</p>
					
					<p>Spirit Friday does not knowingly collect or solicit personal information from anyone under the age of 13 or knowingly allow such persons to register for our services.  . If you are under 13, please do not attempt to register for the Services or send any information about yourself to us, including your name, address, telephone number, or email address. No one under age 13 may provide any personal information to us or on the Services. In the event that we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us at <a href="mailto:support@spiritfriday.com">support@spiritfriday.com</a></p>       	

					<p>C. Email and other communications</p>

					<p>We may contact you, by email or other means; for example, we may send you promotional offers on behalf of other businesses, or communicate with you about your use of the Website. Also, we may receive a confirmation when you open an email from us. This confirmation helps us make emails more interesting and improve our service. If you do not want to receive email or other mail from us, please indicate your preference by changing your account settings accordingly, contacting us at <a href="mailto:support@spiritfriday.com">support@spiritfriday.com</a>, or by clicking the "unsubscribe" link in an email we send to you. Please note that if you do not want to receive legal notices from us, those legal notices will still govern your use of the Website, and you are responsible for reviewing such legal notices for changes.</p>
					
					<h2 class="center">II. Sharing Gathered Information</h2>
					
					<p>We neither rent nor sell your Personal Information in personally identifiable form to anyone. We do not use or share the personally identifiable information provided to us online in ways unrelated to the ones outlined below, without also providing you an opportunity to opt-out. We share your Personal Information in personally identifiable form with third parties as described below.</p>
					
					<p>A.  Affiliated Businesses and Third Party Websites We Do Not Control</p>
					
					<p>In certain situations, businesses or third party websites we’re affiliated with may sell items or provide services to you through the Website (either alone or jointly with us). You can recognize when an affiliated business is associated with such a transaction or service, and we will share your Personal Information with that affiliated business only to the extent that it is related to such transaction or service. For example, if you purchase a Voucher through the Service, we may share certain information about you with the applicable Merchant, in order to allow such Merchant to redeem that Voucher. Another such service may include the ability for you to automatically transmit Third Party Account Information to your Website profile or to automatically transmit information in your Website profile to your third party account. We have no control over the policies and practices of third party websites or businesses as to privacy or anything else, so if you choose to take part in any transaction or service relating to an affiliated website or business, please review all such business’ or websites’ policies.</p>
					
					<p>B. User Profiles and Submissions</p>
					
					<p>Certain user profile information, including without limitation a user’s name, location, and any video or image content that such user has uploaded to the Website, may be displayed to other users to facilitate user interaction within the Website or address your request for Spirit Friday’s services. Your account privacy settings allow you to limit the other users who can see the Personal Information in your user profile and/or what information in your user profile is visible to others. Any content you upload to your public user profile, along with any Personal Information or content that you voluntarily disclose online in a manner other users can view (on discussion boards, in messages and chat areas, etc.) becomes publicly available, and can be collected and used by others. Your user name may also be displayed to other users if and when you send messages or comments or upload images or videos through the Website and other users can contact you through messages and comments. Additionally, if you sign into the Website through a third party social networking site or service, your list of “friends” from that site or service may be automatically imported to the Website, and such “friends,” if they are also registered users of the Website, may be able to access certain non-public information you have entered in your Website user profile. Again, we do not control the policies and practices of any other third party site or service.</p>
					
					<p>C. Protection of Spirit Friday or Others</p>
					
					<p>We reserve the right to access, read, preserve, and disclose any information that we reasonably believe is necessary to comply with law or court order; enforce or apply our conditions of use and other agreements; or protect the rights, property, or safety of Spirit Friday, our employees, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction.</p>
					
					<p>D. With Your Consent</p>
					
					<p>Except as set forth above, you will be notified when your Personal Information may be shared with third parties in personally identifiable form, and will be able to prevent the sharing of this information.</p>
					
					<h2 class="center">III.  Data security</h2>
					
					<p>We take a reasonable effort to protect your personal information stored in our database. Access to your personal information is limited to our authorized staff who need that information to perform their job functions.  Your password is stored in a encrypted form which makes it computationally impossible for anyone, including us, to derive the plain text password from it.</p>
					
					<h2 class="center">IV.  Notice of Change</h2>
					
					<p>Spirit Friday  reserves the right to change or modify the Policy at any time, without prior notice, by posting the modified Policy on the Website. Your continued use of the Website indicates your acceptance of any revised Policy.</p>
					
					<p>Spirit Friday  may provide you with notifications that include, without limitation, any changes that are made to the Policy or other Website related service, by postings on the Website or via email to a user.</p>
					
					<h2 class="center">V. Questions or Concerns</h2>
					
					<p>If you have any questions or concerns regarding our privacy policies, please send us a detailed message to <a href="mailto:support@spiritfriday.com">support@spiritfriday.com</a>. We will make every effort to resolve your concerns.</p>
					
					<h2>Effective Date: May 11, 2012</h2>
					<p>-----------------------------------------------------------------------------------------</p>
					
					<h2 class="center">TERMS OF USE</h2>
					
					<p>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THE SERVICES OFFERED BY SPIRIT FRIDAY, LLC. OR ITS AFFILIATES (COLLECTIVELY “SPIRIT FRIDAY,” “WE,” OR “US”). BY ACCESSING OR USING THE WEBSITE (AS DEFINED BELOW) OR THE SERVICES (AS DEFINED BELOW) IN ANY MANNER, YOU AS AN INDIVIDUAL OR AS A SINGLE USER ON BEHALF OF THE ENTITY OR COMPANY THAT YOU REPRESENT (“YOU” OR “YOUR” AS APPLICABLE) AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY, AND A PARTY TO, THE TERMS AND CONDITIONS IN THIS TERMS OF USE (“AGREEMENT”) TO THE EXCLUSION OF ALL OTHER TERMS. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF YOU DO NOT UNCONDITIONALLY AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT YOU WILL HAVE NO RIGHT TO USE THE SERVICES. USE OF THE SERVICES IS EXPRESSLY CONDITIONED UPON YOUR ASSENT TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT TO THE EXCLUSION OF ALL OTHER TERMS.</p>
					
					<h3>ACCESS TO THE SERVICES</h3>
					
					<p>The spiritfriday.com website and domain names and any other linked and related pages, features, content, or application services (including without limitation any mobile applications services) offered from time to time by Spirit Friday in connection therewith (collectively, the “Website”) are owned and operated by Spirit Friday. Subject to the terms and conditions of this Agreement, Spirit Friday may offer to provide certain services, as described more fully on the Website, and which are selected by you through the process provided on the Website (together with the Website, the “Services”), solely for your own use, and not for the use or benefit of any third party. The term “Services” shall include, without limitation, use of the Website and any service Spirit Friday performs for you and the content, software, tools, and features offered by Spirit Friday on the Website (including, without limitation the Video Player (as defined below)). Spirit Friday may change, suspend or discontinue the Services at any time, including the availability of any feature, database, or Content (as defined below). Spirit Friday may also impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability. SPIRIT FRIDAY RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO MODIFY THIS AGREEMENT AT ANY TIME BY POSTING A NOTICE ON THE WEBSITE, OR BY SENDING YOU A NOTICE VIA EMAIL OR POSTAL MAIL. YOU SHALL BE RESPONSIBLE FOR REVIEWING AND BECOMING FAMILIAR WITH ANY SUCH MODIFICATIONS. USE OF THE SERVICES BY YOU FOLLOWING SUCH NOTIFICATION CONSTITUTES YOUR ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT AS MODIFIED.</p>
					
					<p>Spirit Friday does not knowingly collect or solicit personal information from anyone under the age of 13 or knowingly allow such persons to register for the Services. If you are under 13, please do not attempt to register for the Services or send any information about yourself to us, including your name, address, telephone number, or email address. No one under age 13 may provide any personal information to Spirit Friday or on the Services. In the event that we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us at support@spiritfriday.com. Some features of the Website require users to be eighteen (18) years of age or older, and if you are under eighteen (18) years of age you agree that you will not use or attempt to access such features.</p>
					
					<p>You represent and warrant to Spirit Friday that: (i) you are an individual (i.e., not a corporation) and you are of legal age to form a binding contract or have your parent’s permission to do so, and you are at least 13 years or age or older; (ii) all registration information you submit is accurate and truthful; and (iii) you will maintain the accuracy of such information. You also certify that you are legally permitted to use and access the Services and take full responsibility for your access, selection and use of the Services. This Agreement is void where prohibited by law, and the right to access and use the Services is revoked in such jurisdictions.</p>
					
					<p>You shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. You shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services. The Services are offered by Spirit Friday from its facilities in the United States of America. Spirit Friday makes no representations that the Services are appropriate or available for use in other locations. Users who access or use the Services from other jurisdictions do so at their own volition and are responsible for compliance with local laws.</p>
					
					<h3>WEBSITE AND SERVICES CONTENT</h3>
					
					<p>The Website, the Services, and their contents are intended solely for your personal, non-commercial use (except as specifically and expressly agreed in writing by Spirit Friday in connection with a specific feature of the Service only) and may only be used in accordance with the terms of this Agreement. All materials displayed or performed on the Services (including, but not limited to text, blogs, graphics, articles, photographs, images, illustrations and video (also known as the “Content,” and which includes User Submissions (as defined below)) are protected by copyright. You shall abide by all copyright notices, trademark rules, information, and restrictions contained in any Content accessed through the Services, and shall not use, copy reproduce, modify translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purposes whatsoever any Content or User Submissions or other proprietary rights not owned by you, (i) without the express prior written consent of the respective owners, and (ii) in any way that violates any third party right.</p>
					
					<p>You shall not remove, obscure, or alter any notices or links (e.g., links to Spirit Friday’s Privacy Policy and Terms of Use) on the Website or any of its features or tools or other Services. In addition, you agree not to access, display, distribute or otherwise exploit User Submissions or any other Content through any technology.</p>
					
					<p>The Website and the Services are protected by copyright as collective works and/or compilations, pursuant to U.S. copyright laws, international conventions, and other intellectual property laws. You may not modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section 2 of the Agreement), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p>
					
					<p>You may download or copy the Content, and other items displayed on the Services or Website for download, for personal non-commercial use only, provided that you maintain all copyright and other notices contained in such Content. You shall not store any significant portion of any Content in any form. Copying or storing of any Content for other than personal, noncommercial use is expressly prohibited without prior written permission from Spirit Friday, or from the copyright holder identified in such Content’s copyright notice. If you link to the Services, Spirit Friday may revoke your right to so link at any time, at Spirit Friday’s sole discretion. Spirit Friday reserves the right to require prior written consent before linking to the Services.</p>
					
					<p>In the course of using the Services, you and other users may provide information which may be used by Spirit Friday in connection with the Services and which may be visible to certain other users. You understand that by posting information, images, video, blogs, or other content on the Services or otherwise providing User Submissions to Spirit Friday or in connection with the Services (collectively, “User Submissions”), Spirit Friday hereby is and shall be granted a non exclusive, worldwide, royalty free, perpetual, irrevocable, sublicenseable, transferable right to fully exploit such User Submissions (including all related intellectual property rights) in connection with the Services, the Website, and Spirit Friday’s (and its successors’ and assigns’) business, including without limitation for promoting and redistributing part or all of the Services (and derivative works thereof) in any media formats and through any media channels, and to allow others to do so, however, Spirit Friday will only share personally identifiable information that you have not made publicly available in accordance with Spirit Friday’s current privacy policy at http://www.spiritfriday.com/privacy. You also hereby do and shall grant each user of the Services a non-exclusive license to access your User Submissions through the Services, and to use, modify, reproduce, distribute, prepare derivative works of, display, and perform such User Submissions as permitted through the functionality of the Services and under this Agreement. Furthermore, you understand that Spirit Friday retains the right to reformat, modify, create derivative works of, excerpt, and translate any User Submissions submitted by you. For clarity, the foregoing license granted to Spirit Friday does not affect your ownership of or right to grant additional non-exclusive licensees to the material in your User Submissions, unless otherwise agreed in writing. You understand that all information publicly posted or privately transmitted through the Services is the sole responsibility of the person from which such content originated and that Sugar will not be liable for any errors or omissions in any content. You understand that Spirit Friday cannot guarantee the identity of any other users with whom you may interact in the course of using the Services. Additionally, Spirit Friday cannot guarantee the authenticity of any data which users may provide about themselves. You acknowledge that all Content and User Submissions accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to any party resulting therefrom.<p>
					
					<p>In the course of using the Services, you will be fully responsible for any licensing of images that you publish on your blog.</p>
					
					<p>Under no circumstances will Spirit Friday be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred in connection with use of or exposure to any Content posted, emailed, accessed, transmitted or otherwise made available via the Services. You are solely responsible for taking all precautions necessary and/or reasonable to protect yourself, your computer systems and other property from viruses, worms, Trojan horses, and other harmful content and code. You acknowledge that Spirit Friday does not endorse or guarantee any user blogs, video, or other User Submissions and you may not state or imply any such endorsement or guarantee. Spirit Friday shall have no obligation to monitor any User Submissions, however, Spirit Friday and its agents reserve the right to monitor User Submissions from time to time and may remove or block any User Submissions on or accessible through the Services, including disabling access to User Submissions that you have downloaded through the Services.</p>
					
					<h3>YOUR WARRANTY</h3>
					
					<p>You warrant, represent and agree that you will not contribute any User Submissions (including, without limitation, anything in connection with your blog(s)) or otherwise use the Services in a manner that (i) infringes or violates the intellectual property rights or proprietary rights, or rights of publicity or privacy, or other rights of any third party; (ii) violates any law, statute, ordinance or regulation; (iii) is harmful, fraudulent, deceptive, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, or otherwise objectionable; (iv) misrepresents the source or identity of any content; (v) involves commercial activities and/or sales without Spirit Friday’s prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes; (vi) uploads, installs, constitutes, or embeds malware, virus, worms, Trojan horses, or other harmful content or code, or (vii) impersonates, or falsely indicates an affiliation with, any person or entity, including, without limitation, any employee or representative of Spirit Friday. Spirit Friday reserves the right to remove any Content from the Services at any time, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if Spirit Friday is concerned that you may have breached the immediately preceding sentence), or for no reason at all. You, not Spirit Friday, remain solely responsible for all User Submissions that you upload, post, email, transmit, or otherwise disseminate using, or in connection with, the Services, and you warrant that you possess all rights necessary to provide such content to Spirit Friday and to grant Spirit Friday the rights to use such information in connection with the Services and as otherwise provided herein.</p>
					
					<p>Without limiting the foregoing, you agree that you will not use our sites to take any of the following actions:</p>
					<ol>
						<li>Defame, abuse, harass, stalk, threaten, or otherwise violate the legal right of others;</li>
						<li>Publish, post, upload, e-mail, distribute, or disseminate (collectively, "Transmit") any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;</li>
						<li>Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, our sites, any software or hardware, or telecommunications equipment;</li>
						<li>Advertise or offer to sell any goods or services for any commercial purpose unless you have our written consent to do so;</li>
						<li>Transmit surveys, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters;</li>
						<li>Download any file that you know or reasonably should know cannot be legally obtained in such manner;</li>
						<li>Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material;</li>
						<li>Restrict or inhibit any other user from using and enjoying any public area within our sites;</li>
						<li>Collect or store personal information about other end users;</li>
						<li>Interfere with or disrupt our sites, servers, or networks;</li>
						<li>Impersonate any person or entity, including, but not limited to, a Polyvore representative, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
						<li>Forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through our sites or to manipulate your presence on our sites;</li>
						<li>Take any action that imposes an unreasonably or disproportionately large load on our infrastructure;</li>
						<li>Engage in any illegal activities.</li>
					</ol>
					
					<h3>RESTRICTIONS</h3>
					
					<p>You are responsible for all of your activity in connection with the Services. Any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your right to access or use the Services. You may not post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any Spirit Friday user. Use of the Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene, or engage in any kind of illegal activity is expressly prohibited. You will not run Maillist, Listserv, any form of auto-responder, or “spam” on the Services, or any processes that run or are activated while you are not logged on to the Website or that otherwise interfere with the proper working of or place an unreasonable load on the Services infrastructure. Further, the use of manual or automated software, devices, or other processes to “crawl” or “spider” any page or Content of the Services is strictly prohibited. You will not decompile, reverse engineer, or otherwise attempt to obtain the source code of the Services. You will be responsible for withholding, filing, and reporting all taxes duties and other governmental assessments associated with your activity in connection with the Services.</p>
					
					<h3>WARRANTY DISCLAIMERS</h3>
					
					<p>Spirit Friday has no special relationship with or fiduciary duty to you. You acknowledge that Spirit Friday has no control over, and no duty to take any action regarding: which users gain access to the Services; what Content you access via the Services (including, without limitation, viruses, malware, harmful code and user generated content); what effects the Content may have on you; how you may interpret or use the Content; or what actions you may take as a result of having been exposed to the Content. You release Spirit Friday from all liability for you having acquired or not acquired Content through the Services. The Services may contain, or direct you to websites containing, information that some people may find offensive or inappropriate. Spirit Friday makes no representations concerning any content contained in or accessed through the Services, and Spirit Friday will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Services. Spirit Friday makes no representations or warranties regarding the accuracy of descriptions displayed anywhere on the Services, or regarding suggestions or recommendations of services or products offered or purchased through the Services (including, without limitation, the actual size, quality, color, texture, or results of use of such products or services), or that the Services or any Content will be uninterrupted or error-free. Products and services purchased (whether or not following such recommendations and suggestions) are provided “AS IS” without any warranty of any kind from Spirit Friday or others unless, with respect to others (only), otherwise made expressly and unambiguously in writing by a designated third party for a specific product. THE SERVICES, CONTENT, WEBSITE, PRODUCTS AND SERVICES OBTAINED THROUGH THE WEBSITE, AND ANY SOFTWARE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY OR COMPLETENESS OF CONTENT, NON-INFRINGEMENT, OR THE AVAILABILITY OR QUALITY OF ANY PRODUCTS OR SERVICES AVAILABLE VIA THE SERVICES. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
					
					<h3>COLORS</h3>
					
					<p>Spirit Friday tags merchants’ online clothing in specific color combinations to guide you in finding clothing in your desired colors.  Sometimes the product images from the merchants to not appear the true in color to the name of to the listed color or actual item.  Spirit Friday serves you by directing you to the merchant site where you can decide if the color portrayed through the images matches that which you desire.  Though we aim to minimize these errors through contacting merchants for color questions and allowing users to report a mistagged color, we are not responsible for any mistagged products.  Spirit Friday does not handle any purchases or returns, they are all done by the merchants’ sites. By shopping on Spirit Friday, you are agreeing to these terms of use.</p>
					
					<h3>CORRECTION OF ERRORS AND INACCURACIES</h3>
					
					<p>The information of the spiritfriday.com website may contain typographical errors or inaccuracies and may not be complete or current.  We therefore reserve the right to correct any errors, inaccuracies or omissions and to change and update the information at any time without prior notice.  Please note that such errors, inaccuracies or omissions may relate to product description, price, and availability.  We apologize for any inconvenience this may cause you.</p>
					
					<h3>PRIVACY POLICY</h3>
					<p>For information regarding Spirit Friday’s treatment of personally identifiable information, please review Spirit Friday’s current privacy policy at http://www.spiritfriday.com/privacy, which is hereby incorporated into this Agreement by reference; your acceptance of this Agreement constitutes your acceptance and agreement to be bound by Spirit Friday’s privacy policy.</p>
					
					<h3>REGISTRATION AND SECURITY</h3>
					<p>As a condition to using some aspects of the Services, you may be required to register with Spirit Friday and select a password and user name (“Spirit Friday User ID”). If you are accessing the Services through a third party site or service (such as “Facebook Connect”), Spirit Friday may require that your Spirit Friday User ID be the same as your user name for such third party site or service. You shall provide Spirit Friday with accurate, complete, and updated registration information. Failure to do so shall constitute a breach of this Agreement, which may result in immediate termination of your account. You may not (i) select or use as a Spirit Friday User ID a name of another person with the intent to impersonate that person; or (ii) use as a Spirit Friday User ID a name subject to any rights of a person other than you without appropriate authorization. Spirit Friday reserves the right to refuse registration of, or cancel a Spirit Friday User ID in its discretion. You shall be responsible for maintaining the confidentiality of your password. If you access the Service through a third party site or service, you will provide your third party account credentials to Spirit Friday, and you are consenting to have the information in those accounts transmitted into your Spirit Friday account, and you agree that you shall only use accounts owned by you, and not by any other person or entity.</p>
					
					<h3>INDEMNITY</h3>
					<p>You will indemnify and hold Spirit Friday, its parents, subsidiaries, affiliates, officers and employees, harmless (including, without limitation, from all damages, liabilities, settlements, costs and attorneys’ fees) from any claim or demand made by any third party due to or arising out of your access to the Services, use of the Services, the violation of this Agreement by you, or the infringement by you, or any third party using your account, of any intellectual property or other right of any person or entity.</p>
					
					<h3>LIMITATION OF LIABILITY</h3>
					<p>TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, IN NO EVENT SHALL SPIRIT FRIDAY OR ITS SUPPLIERS, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE WITH RESPECT TO THE WEBSITE OR THE SERVICES OR THE SUBJECT MATTER OF THIS AGREEMENT UNDER ANY CONTRACT, NEGLIGENCE, TORT, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY AMOUNT IN THE AGGREGATE IN EXCESS OF THE GREATER OF THE FEES PAID BY YOU THEREFOR OR $100; (II) FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER; (III) FOR DATA LOSS OR COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; OR (IV) FOR ANY MATTER BEYOND SPIRIT FRIDAY’S REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
					
					<h3>REFERRAL CREDITS</h3>
					<p>Spirit Friday may provide you referral credits (“Referral Credits”) when you invite your friends to sign up for certain types of Spirit Friday accounts (“Credit-Eligible Accounts”). Referral Credits may be awarded to you when your friends join and make their first Voucher purchases. Referral Credits are granted in Spirit Friday’s sole discretion. In order for you to be eligible to receive Referral Credits for friends creating new Credit-Eligible Accounts, the new friend must create a Credit-Eligible Account via the unique referral link Spirit Friday provides to you and make a purchase. Referral Credits are loyalty or promotional discounts or credits offered by Spirit Friday, and do not constitute an account, a payment instrument or other property owned by any Spirit Friday user. Spirit Friday reserves the right to revoke your Referral Credits if it determines that you have engaged in fraudulent referral activity (e.g. inviting fake people to create Credit-Eligible Accounts) or otherwise violated the Agreement, or if Spirit Friday terminates your membership. Referral Credits expire six (6) months after they are granted. Referral Credits are not transferable or sellable, are not gift cards, have no cash value, are not cash equivalents, and cannot be redeemed for cash or cash equivalents. You may not sell, give, or otherwise transfer your Referral Credits to any other individual or Spirit Friday user. Spirit Friday reserves the right at any time without notice to you to change the terms applicable to the Referral Credits, including expiration period and/or your ability to redeem existing Referral Credits.</p>
					
					<h3>INTERACTION WITH THIRD PARTIES</h3>
					<p>This website contains links to outside services and resources.  You acknowledge that (A) Spirit Friday is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites; and (B) Spirit Friday is not responsible for any form of transmission received from any linked site.  Spirit Friday is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Spirit Friday of the site.  Any concerns regarding any such link should be directed to the particular third party website.</p>

					<h3>TERMINATION</h3>
					<p>This Agreement shall remain in full force and effect while you use the Services (or any part of the Services). You may terminate your use of the Services or your membership at any time by following the instructions on the Services. Spirit Friday may terminate or suspend your access to the Services (and/or any feature thereof) or your membership at any time, for any reason, and without warning, which may result in the forfeiture and destruction of all information associated with your membership. Spirit Friday may also terminate or suspend any and all Services or your access thereto immediately, without prior notice or liability, if you breach any of the terms or conditions of this Agreement. Upon termination of your account, your right to access and use the Services, the Website, and any Content will immediately cease. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p>
					
					<h3>COPYRIGHT DISPUTE POLICY</h3>
					<p>Spirit Friday has adopted the following general policy toward copyright infringement in accordance with the Digital Millennium Copyright Act or DMCA (posted at www.lcweb.loc.gov/copyright/legislation/dmca.pdf). The address of Spirit Friday Designated Agent to Receive Notification of Claimed Infringement (“Designated Agent”) is listed at the end of this Section. It is Spirit Friday’s policy to (1) block access to or remove material that it believes in good faith to be copyrighted material that has been illegally copied and distributed by any of our advertisers, affiliates, content providers, members or users; and (2) remove and discontinue service to repeat offenders.</p>
					
					<p><span class="bold">Procedure for Reporting Copyright Infringements:</span></p>
					<p>If you believe that material or content residing on or accessible through the Services infringes a copyright, please send a notice of copyright infringement containing the following information to the Designated Agent listed below:</p>
					<ul>
						<li>A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright that has been allegedly infringed;</li>
						<li>Identification of works or materials being infringed;</li>
						<li>Identification of the material that is claimed to be infringing including information regarding the location of the infringing materials that the copyright owner seeks to have removed, with sufficient detail so that Spirit Friday is capable of finding and verifying its existence;</li>
						<li>Contact information about the notifier including address, telephone number and, if available, email address;</li>
						<li>A statement that the notifier has a good faith belief that the material identified in (3) is not authorized by the copyright owner, its agent, or the law; and</li>
						<li>A statement made under penalty of perjury that the information provided is accurate and the notifying party is authorized to make the complaint on behalf of the copyright owner.</li>
					</ul>
					
					<p><span class="bold">Once Proper Bona Fide Infringement Notification is Received by the Designated Agent:</span></p>
					<p>It is Spirit Friday’s policy:</p>
					<ul>
						<li>to remove or disable access to the infringing material;</li>
						<li>to notify the content provider, member or user that it has removed or disabled access to the material; and</li>
						<li>that repeat offenders will have the infringing material removed from the system and that Spirit Friday will terminate such content provider’s, member’s or user’s access to the service.</li>
					</ul>
					
					<p><span class="bold">Procedure to Supply a Counter-Notice to the Designated Agent:</span></p>
					<p>If the content provider, member or user believes that the material that was removed or to which access was disabled is either not infringing, or the content provider, member or user believes that it has the right to post and use such material from the copyright owner, the copyright owner’s agent, or pursuant to the law, the content provider, member or user must send a counter-notice containing the following information to the Designated Agent listed below:</p>
					<ul>
						<li>A physical or electronic signature of the content provider, member or user;</li>
						<li>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled;</li>
						<li>A statement that the content provider, member or user has a good faith belief that the material was removed or disabled as a result of mistake or a misidentification of the material; and</li>
						<li>Content provider’s, member’s or user’s name, address, telephone number, and, if available, email address and a statement that such person or entity consents to the jurisdiction of the Federal Court for the judicial district in which the content provider’s, member’s or user’s address is located, or if the content provider’s, member’s or user’s address is located outside the United States, for any judicial district in which Spirit Friday is located, and that such person or entity will accept service of process from the person who provided notification of the alleged infringement.</li>
					</ul>
					
					<p>If a counter-notice is received by the Designated Agent, Spirit Friday may send a copy of the counter-notice to the original complaining party informing that person that Spirit Friday may replace the removed material or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed material may be replaced or access to it restored in 10 to 14 business days or more after receipt of the counter-notice, at Spirit Friday’s discretion.</p>
					
					<p>Please contact Spirit Friday’s Designated Agent to Receive Notification of Claimed Infringement at the following address:</p>
					<p>Spirit Friday, LLC Headquarters</p>
					<p>924 Sylvan Ave</p>
					<p>Ann Arbor, MI 48104</p>
					<p><a href="mailto:copyright@spiritfriday.com">copyright@spiritfriday.com</a></p>
					
					<h3>ARBITRATION AND MISCELLANEOUS</h3>
					<p>For any dispute you have with Spirit Friday, you agree to first contact us at <a href="mailto:support@spiritfriday.com">support@spiritfriday.com</a> and attempt to resolve the dispute with us informally. In the unlikely event that Spirit Friday has not been able to resolve a dispute it has with you after attempting to do so informally, we each agree to resolve any claim, dispute, or controversy (excluding claims for injunctive or other equitable relief) arising out of or in connection with or relating to these Terms, or the breach or alleged breach thereof (collectively, “Claims”), by binding arbitration by the American Arbitration Association (“AAA”) under the Commercial Arbitration Rules and Supplementary Procedures for Consumer Related Disputes then in effect for the AAA, except as provided herein. Unless you and Spirit Friday agree otherwise, the arbitration will be conducted in the county where you reside. Each party will be responsible for paying any AAA filing, administrative and arbitrator fees in accordance with AAA rules, except that Spirit Friday will pay for your reasonable filing, administrative, and arbitrator fees if your claim for damages does not exceed $75,000 and is non-frivolous (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)). The award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys’ fees and reasonable costs for expert and other witnesses, and any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Section shall prevent either party from seeking injunctive or other equitable relief from the courts for matters related to data security, intellectual property or unauthorized access to the Service. ALL CLAIMS MUST BE BROUGHT IN THE PARTIES’ INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND PINTEREST ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION</p>
					
					<h3>CORRESPONDENCE</h3>
					<p>Although we will make every effort to respond quickly to applicable email messages, spiritfriday.com is under no obligation to respond to all pieces of correspondence received through this site, or to maintain your submitted comments in confidence, or to pay compensation of any kind for your comments or submissions.  While we welcome your comments and feedback regarding spiritfriday.com, our merchandise and our services, we do not wish to receive any confidential or proprietary ideas, suggestions, materials, or information via this website or any email connection.  Please note that all of your comments, feedback, ideas, suggestions, and other submissions that are disclosed or submitted to our company through spiritfriday.com shall become and remain the property of Spirit Friday.  Any such disclosure or submission by you is a declaration of the full release of all proprietary claims and/or intellectual rights regarding your submission.  However, we will not use your name in connection with any such materials, information, suggestions, ideas or comments unless we first obtain your permission or otherwise are required by law to do so.</p>
					
					<h3>QUESTIONS</h3>
					<p>If you have any questions or notices of violation of this Agreement, please contact the editor of the website or service in question, or send an email to <a href="mailto:support@spiritfriday.com">support@spiritfriday.com</a>, or by mail to Spirit Friday, LLC, 924 Sylvan Ave, Ann Arbor, MI, 48104.</p>
					
					<h3>FTC DISCLOSURE REQUIREMENTS</h3>
					<p>Spirit Friday aims to provide unbiased editorials. However, we wish to disclose that we may run advertisements on our sites concerning some of those products or companies that sell them (and other products sold by such companies) for which we sometimes receive compensation.</p>
					
					<p class="italic">Effective: May 9, 2012</p>
				</div>
			</div>
		</div> <!-- end container -->
	</body>
</html>